# Chicken 

## Broccoli Stir Fry {#brocstirfry}

### Ingredients

- 1 pound, chicken breast (sliced)
- 1 pound, broccoli
- 4 tablespoons, oyster sauce
- 2 tablespoons, fish sauce
- 1 tablespoon, sugar
- 4 cloves, garlic (minced)
- 1 tablespoon, cooking oil

### Instructions

Heat oil on medium high heat. Add garlic and cook till it starts to brown (stir frequently). Add chicken, oyster sauce, fish sauce and sugar. Cook till chicken is cooked. Add broccoli and cook for a few more minutes. Serve with white rice. 

## Blackened Chicken {#blackenedchicken}

Original recipe from: https://www.countryliving.com/food-drinks/recipes/a44250/blackened-chicken-fennel-slaw-recipe/

### Ingredients

- 1.25 pounds,    chicken breast
- 1.5 teaspoons,  blackening seasoning
- 3 tablespoons,    olive oil
- 1,               fennel bulb (thinly sliced large) 
- .75 cups,        fennel fronds (chopped)
- 3,                celery ribs (sliced)
- 0.3 cups,         red onion (sliced)
- 2 tablespoons,    lemon juice
- 1,                avocado (sliced)
- 0.3 cups,         feta cheese
- salt and black pepper

### Instructions

1. Season chicken cutlets with blackening seasoning, and kosher salt and black pepper. Cook in 1 tablespoon olive oil in a large skillet over medium-high heat until cooked through, 3 to 4 minutes per side.
2. Meanwhile, toss together thinly sliced large fennel bulb, chopped fennel fronds, celery ribs, red onion, 2 tablespoons olive oil, and fresh lemon juice. Stir in avocado and crumbled feta. Season with kosher salt and black pepper. Serve alongside chicken.

## Greek Chicken Gyros {#chickengyros}

Original recipe from: https://www.modernhoney.com/greek-chicken-gyros-with-tzatziki-sauce/

### Ingredients

**Chicken Marinade**:

- 2 pounds,         chicken breast (cut into pieces)
- 0.25 cups,         greek yogurt
- 3 tablespoons,    lemon juice
- 2 tablespoons,    olive oil
- 1 tablespoon,     red wine vinegar
- 1 1/2 teaspoon,   salt
- 1 teaspoon,       ground black pepper
- 2 teaspoons,      oregano

**Tzatziki Sauce**:

- 1.5 cups,       greek yogurt
- 2 tablespoons,    olive oil
- 1 tablespoon,     lemon juice
- 1 tablespoons,    red wine vinegar
- 1 teaspoon,    salt
- 1 tablespoon,    dill (diced)
- 3 cloves,                garlic (finely diced)
- 1,                cucumber (grated and squeezed to drain)

**Greek Salad**:

- 3,                tomatoes (diced)
- 2,                cucumber (peeled and diced)
- 0.25,              red onion (diced)
- 2 tablespoons,    parsley (diced)
- 1 tablespoon,     olive oil
- salt and pepper to taste
- 0.5 cups, feta cheese

- 4, pita bread

### Instructions

1. Place chicken, yogurt, lemon juice, olive oil, vinegar, salt, pepper, and oregano in bag and let marinate at least 30 minutes, preferably 2-4 hours. The ideal time is 24 hours.
2. To make tzatziki sauce, stir together yogurt, olive oil, lemon juice, vinegar, salt, dill, and garlic. Stir in grated cucumber and taste for seasonings. Squeeze the cucumber to remove excess water before adding to rest of ingredients.
3. To make greek salad, place tomatoes, cucumber, red onion, parsley, olive oil, salt and pepper in bowl. Stir to coat. Season to taste.
4. Chicken can be cooked on grill or in skillet. To cook on grill -- place chicken on kebobs and heat grill to medium heat. Cook for 5-7 minutes per side or until chicken is full cooked.
5. To cook chicken on skillet. Heat skillet to medium high heat. Sprinkle with oil. Add chicken and cook for 8-10 minutes, or until chicken is fully cooked and golden brown.
6. Place chicken in pita bread. You can warm the pita bread to make it pliable. Top with tzatziki sauce and greek salad. Add additional feta, if desired.

## Jerk Chicken {#jerkchicken}

Original recipe from: https://www.africanbites.com/jerk-chicken/

### Ingredients

- 4 pounds,	    chicken thighs  
- 1,           		lemon
- 0.5	tablespoon,	cinnamon powder  
- 0.3 teaspoon,	              thyme  
- 3,	              green onion (chopped)  
- 1,	              onion (coarsely chopped)  
- 4,		          habanero pepper (chopped)  
- 1.5	tablespoons,	soy sauce
- 1	tablespoon,  	bouillon powder (optional)  
- 3	tablespoons,  	dark brown sugar  
- 6 cloves,           		garlic (chopped)  
- 1	teaspoon,     	 nutmeg (freshly grated)
- 1	tablespoon,	  allspice (coarsely ground)  
- 1.5	tablespoons,	ginger (chopped)  
- 1	tablespoon,	  ground black pepper  
- 0.5	cups,	        water
- salt and pepper to season  

### Instructions

1. Trim chicken of excess fat and pat dry with a cloth or paper napkin. Rub with lemon, salt and pepper
2. In a food processor or blender, combine the following: cinnamon, thyme, green onions, onion, habanero pepper, soy sauce, maggi/bouillon, brown sugar, garlic, nutmeg. allspice, fresh ginger ,ground pepper and Liquid . Pulse for about 30 seconds until blended.
3. Drench the chicken with jerk marinate, place in a zip lock bag and refrigerate for at least 3 hours, preferably overnight. Try not to touch the jerk blend with your hands because it is extremely spicy hot. If possible, use gloves.
4. When ready to grill, remove chicken from the jerk marinade and place on medium to high lightly oil grill. Reserve the marinade
5. Cook chicken on the prepare grill 12- 20minutes, until juices run clear (internal temp of 165 degree F), turning often to optimize cooking and browning.You may also broil, or roast the chicken in a hot oven (425 degrees F).
6. In a small sauce pan simmer the remaining marinade and the one from the chicken for about 7 minutes. Serve with the chicken or mix it before serving with the plantains.

## Sausage, Mushroom, and Black Olive White Pizzas {#whitepizzas}

### Ingredients

- 0.25	cups,	grated parmesan  
- 7	tablespoons,	olive oil  
- 1 clove, garlic (chopped)
- 1,  ciabatta baguette (halved)
- 2, 		 Italian-style chicken sausage links (fully cooked, thinly sliced)
- 0.75	cups,	 mushrooms (sliced)
- 0.25	cups,	sliced black olives  
- 1.5	cups,	 mozzarella (shredded)
- 4 cups,	baby spinach  
- 1	tablespoon,	lemon juice  
- 0.5	teaspoons,	red pepper flakes (optional)

### Instructions

1. Preheat oven to 425F. Stir together Parmesan, 3 tablespoons olive oil, and chopped garlic clove.
2. Halve ciabatta baguette lengthwise and cut into 4 pieces. Place on a foil-lined baking sheet and top with cheese mixture. Top with Italian-style chicken sausage links, mushrooms, and black olives. Sprinkle with shredded mozzarella. Bake until golden, 10 to 12 minutes.
3. Meanwhile, toss together baby spinach, lemon juice and olive oil, and red pepper flakes (optional). Season with kosher salt and black pepper. Top pizza with spinach mixture. Serve immediately.