# Yao Horn {#yao-horn}

Original recipe from: https://www.youtube.com/watch?v=G6fKPnm6LYA

## Hot Pot base

### Ingredients

4 cups          chicken stock (can use coconut water as substitute)

2 tablespoons   cooking oil 

3               garlic cloves (minced)

2               shallot cloves (minced)

7 or 8          dried whole chilis

1 piece         galangal (thinly sliced)

2 stalks        lemongrass (smashed and cut into 2 inches - only keep the white-ish part)

5               kaffir lime leaves

4 tablespoons   dried shrimps (finely minced)

1 tablespoon    palm sugar

1/2 tablespoons shrimp paste

4 tablespoons   fish sauce

1/2 cups        Sha Cha sauce

1 tablespoon    tamarind paste

250 ml          coconut milk

2 tablespoons   roasted peanut (chopped)

### Instructions

1. Soak dried chilis in hot water until they turn soft and squeezy. After they turn soft, cleanly wash and remove the seeds. Then, finely chopped (by hand or using food processor).

2. Heat a large pot on medium low, add cooking oil. Then add garlic and shallot, fry until fragrant and golden brown. Add lemongrass, galangal, and kaffir lime leaves. Continue frying until fragrant. Be careful not to burn the garlic and shallot. Add chopped dried chilis, then stir for a few more minutes. Add palm sugar, shrimp paste and fish sauce (can adjust to your taste). Then, add dried shrimp, Sha Cha sauce, tamarind paste and 100ml of the coconut milk. Stir well on low heat for 5 minutes. Then add chicken stock (or coconut water). Increase the heat and bring to boil. Then, immediately add roasted peanut and the remaining coconut milk. 

## Dipping sauce

### Ingredients

4 tablespoons fermented tofu/bean curds

6 tablespoons lime juice

2 tablespoons sugar

100 ml        milk (or water as substitute)

5 tablespoons melted unsalted butter

(as prefer)   chili and garlic (chopped)

### Instructions

1. In a bowl, mash fermented bean curds into thick paste. Then add sugar and lime juice, and mix well. Then add milk and butter. Mix it well and until everything is well incorporated. Add chili and garlic when serve. 

## Meat and Veggies

You can choose meat and vegetables to your liking. But here are some popular choices:

- beef
- shrimps/prawns
- squids

- crowned daisy
- water spinach
- Chinese/napa cabbage
- Bok choy
- enoki mushrooms
