# Khmer Noodles (Num Bank Juk) {#num-ban-juk}

Original recipe here: https://www.youtube.com/watch?v=LvFY20G_P6s&t=475s

## Ingredients

*Unfortunately, I don't have exact measurements for each of the ingredients. Most of the time, Khmer cooking in a regular household relies on your sense of knowing how much to put of what. I will update this recipe next time I make this after measuring each ingredient as I go. *

- lemongrass
- turmeric
- garlic
- finger root/rhizome (fresh or canned or pickled)
- roasted peanut
- catfish or any white fish
- prahok
- coconut milk
- salt
- sugar
- fish sauce


## Instructions

1. In a large pot, bring water to boil, then cook the fish for 10 minutes (or till well-cooked). Remove fish from pot and let it cool and then remove bones, if any. Keep the fish stock. 

2. In a mortar (or food processor), mash lemongrass quite well. Then add garlic and tumeric, and mash well. Then add finger roots, and mash well. Then add roasted peanut, and mash well. Then add fish and mash well. 

3. Add coconut milk to the fish stock and bring to boil. Add pra-hok by first mixing it in a small bowl with hot water, then only put in the liquid part. Cook for about 5 minutes. Then add fish sauce, salt, and sugar. Cook for 5 minutes. Then add the fish mixture. Cook for 5 minutes. 


## Serving

- rice sticks (noodles) (cook as instructed on package)

- banana flower (thinly sliced)
- chili (crushed/chopped)
- bean sprout 
- cucumber (sliced)

in a serving bowl, start with vegetables that you like, add rice noodles, then top with the fish-based soup. Add chili as preferred. 