# Pork

## Egg rolls {#eggrolls}

### Egg rolls

Original recipe from: https://www.youtube.com/watch?v=pBk04QSLYKo

#### Ingredients

- 1 pound,      ground pork 
- 1,             onion (chopped)
- 2,            eggs
- 4 cloves,            garlic (chopped)
- 2 cups,       carrot (shredded)
- 4 cups,       taro (shredded)
- 50,           spring roll wrappers
- 1 teaspoon,   ground black pepper
- 1 tablespoon, chicken bouillon powder
- 1 tablespoon, soy sauce
- 1 teaspoon,   brown sugar

#### Instructions

Combine all ingredients, except spring roll wrappers, until well-mixed. Roll the egg rolls, then deep fried (or air fried!).

### Dipping sauce

#### Ingredients 

- 3/2 cups    water
- 3/4 cups    sugar
- 1/2 cups    fish sauce
- 1/4 cups    distilled vinegar
- 2           garlic cloves (minced)
- Optional: 5 Thai peppers (minced)

#### Instructions

In a sauce pan, combine water, sugar, fish sauce, distilled vinegar and bring to boil. Add garlic and peppers when serve.

## Slow Cooked Carnitas {#carnitas}

Original recipe from: https://www.skinnytaste.com/mexican-slow-cooked-pork-carnitas/

### Ingredients

- 2.5	pounds,	boneless pork shoulder blade roast
- 2	teaspoons, salt  
- 1 teaspoon, ground black pepper
- 6	cloves,	garlic (cut into sliver)
- 1.5	teaspoons,	cumin  
- 0.5	teaspoons, sazon (homemade or packaged)
- 0.25 teaspoons, oregano  
- 0.75 cups, chicken broth  
- 3, chipotle peppers in adobo sauce (to taste)
- 2, bay leaves  
- 0.25 teaspoons,	dry adobo seasoning (Goya)

### Instructions

1. Season pork with salt and pepper.
2. In a medium sauté pan on medium-high heat, brown pork on all sides for about 10 minutes.
3. Remove from heat and allow to cool.
4. Using a sharp knife, insert blade into pork, cutting small holes and insert garlic slivers all the way in so you no longer see them.
5. Season pork generously with cumin, adobo, sazon, oregano all over.
6. Pour chicken broth in the crockpot, add bay leaves and chipotle peppers.
7. Place pork in crock pot and cover.
8. Cook low for 8 hours.
9. After 8 hours, shred pork using two forks and combine well with the juices that accumulated at the bottom.
10. Remove bay leaves and adjust salt and cumin as needed.
11. Let it cook another 15-30 minutes.