# Beef

## Beef Bulgogi {#bulgogi}

Original recipe from: https://mykoreankitchen.com/bulgogi-korean-bbq-beef/

### Ingredients

#### Main

- 1.76 pounds, rib eye steak (or any tender prime beef cut, thinly sliced, 2mm to 3mm thickness)
- 1,            onion (peeled & thinly sliced)
- 2 stalks,    green onion (thinly sliced)
- 0.5,         carrot (peeled & thinly sliced)
- 1 tablespoon,      toasted sesame oil
- 1 tablespoon,      toasted sesame seeds
- 1 tablespoon,      cooking oil

#### Marinade

- 6 tablespoons,      soy sauce
- 3 tablespoons,      brown sugar
- 2 tablespoons,      rice wine (mirin)
- 1,           Asian pear
- 0.5,         onion
- 1 tablespoon,       garlic (minced)
- 1 teaspoon,        ginger (minced)
- 1/8 teaspoons,     ground black pepper

### Instructions

1. Blend the marinade ingredients in a mixer or food processor until smooth. Set aside.
2. Place the thinly sliced meat in a mixing bowl and pour the marinade over it. Mix them well together while gently massaging the meat with your hands (use gloves). Add the sesame oil and mix it into the meat. Cover the bowl with cling wrap and marinate the meat for at least 4 hours in the fridge. 
3. Preheat a skillet on medium high heat until well heated. Add the cooking oil and spread it well. Add the meat (and vegetables) and cook it on medium high to high heat for 3 to 5 minutess. Toss in the sesame seeds and stir them quickly.
