# Blackened Chicken {#blackenedchicken}

Original recipe from: https://www.countryliving.com/food-drinks/recipes/a44250/blackened-chicken-fennel-slaw-recipe/

## Ingredients

- 1.25 pounds,    chicken breast
- 1.5 teaspoons,  blackening seasoning
- 3 tablespoons,    olive oil
- 1,               fennel bulb (thinly sliced large) 
- .75 cups,        fennel fronds (chopped)
- 3,                celery ribs (sliced)
- 0.3 cups,         red onion (sliced)
- 2 tablespoons,    lemon juice
- 1,                avocado (sliced)
- 0.3 cups,         feta cheese
- salt and black pepper

## Instructions

1. Season chicken cutlets with blackening seasoning, and kosher salt and black pepper. Cook in 1 tablespoon olive oil in a large skillet over medium-high heat until cooked through, 3 to 4 minutes per side.
2. Meanwhile, toss together thinly sliced large fennel bulb, chopped fennel fronds, celery ribs, red onion, 2 tablespoons olive oil, and fresh lemon juice. Stir in avocado and crumbled feta. Season with kosher salt and black pepper. Serve alongside chicken.
