# Greek Chicken Gyros {#chickengyros}

Original recipe from: https://www.modernhoney.com/greek-chicken-gyros-with-tzatziki-sauce/

## Ingredients

**Chicken Marinade**:

- 2 pounds         Chicken Breast cut into pieces
- 1/4 cups         Greek Yogurt
- 3 tablespoons    Fresh Lemon Juice
- 2 tablespoons    Extra Virgin Olive Oil
- 1 tablespoon     Red Wine Vinegar
- 1 1/2 teaspoon   Salt
- 1 teaspoon       Pepper
- 2 teaspoons      Oregano

**Tzatziki Sauce**:

- 1 1/2 cups       Greek Yogurt
- 2 tablespoons    Extra Virgin Olive Oil
- 1 tablespoon     Lemon Juice
- 1 tablespoons    Red Wine Vinegar
- 1-2 teaspoons    Salt
- 1 tablespoons    Fresh Dill diced
- 3                Garlic Cloves finely diced
- 1                cucumber grated and squeezed to drain

**Greek Salad**:

- 3                Tomatoes diced
- 2                Cucumber peeled and diced
- 1/4              Red Onion diced
- 2 tablespoons    Fresh Italian Parsley diced
- 1 tablespoon     Extra Virgin Olive Oil
- Salt and Pepper to taste
- Feta Cheese

- 4-6 Greek Pita Breads Naan bread, or Flatbread

## Instructions

1. Place chicken, yogurt, lemon juice, olive oil, vinegar, salt, pepper, and oregano in bag and let marinate at least 30 minutes, preferably 2-4 hours. The ideal time is 24 hours.
2. To make tzatziki sauce, stir together yogurt, olive oil, lemon juice, vinegar, salt, dill, and garlic. Stir in grated cucumber and taste for seasonings. Squeeze the cucumber to remove excess water before adding to rest of ingredients.
3. To make greek salad, place tomatoes, cucumber, red onion, parsley, olive oil, salt and pepper in bowl. Stir to coat. Season to taste.
4. Chicken can be cooked on grill or in skillet. To cook on grill -- place chicken on kebobs and heat grill to medium heat. Cook for 5-7 minutes per side or until chicken is full cooked.
5. To cook chicken on skillet. Heat skillet to medium high heat. Sprinkle with oil. Add chicken and cook for 8-10 minutes, or until chicken is fully cooked and golden brown.
6. Place chicken in pita bread. You can warm the pita bread to make it pliable. Top with tzatziki sauce and greek salad. Add additional feta, if desired.