# Jerk Chicken {#jerkchicken}

Original recipe from: https://www.africanbites.com/jerk-chicken/

## Ingredients

- 8-10 pieces	    chicken legs and thighs  
- 1           		lemon/lime  
- 1⁄2	tablespoon	cinnamon powder  
- 1	              sprig	fresh thyme  
- 3	              medium	scallions (green onions) chopped  
- 1	              medium	onion coarsely chopped  
- 2-4		          habanero pepper chopped  
- 1 1⁄2	tablespoon	Maggi or soy sauce
- 1	tablespoon  	bouillon powder optional  
- 3	tablespoons  	dark brown sugar  
- 6           		garlic cloves chopped  
- 1	teaspoon     	freshly grated nutmeg  
- 1	tablespoon	  allspice coarsely ground  
- 1 1⁄2	tablespoon	fresh ginger chopped  
- 1	tablespoon	  coarsely ground pepper  
- 1⁄2	cup	        water
- Salt and pepper to season  

## Instructions

1. Trim chicken of excess fat and pat dry with a cloth or paper napkin. Rub with lemon, salt and pepper
2. In a food processor or blender, combine the following: cinnamon, thyme, green onions, onion, habanero pepper, soy sauce, maggi/bouillon, brown sugar, garlic, nutmeg. allspice, fresh ginger ,ground pepper and Liquid . Pulse for about 30 seconds until blended.
3. Drench the chicken with jerk marinate, place in a zip lock bag and refrigerate for at least 3 hours, preferably overnight. Try not to touch the jerk blend with your hands because it is extremely spicy hot. If possible, use gloves.
4. When ready to grill, remove chicken from the jerk marinade and place on medium to high lightly oil grill. Reserve the marinade
5. Cook chicken on the prepare grill 12- 20minutes, until juices run clear (internal temp of 165 degree F), turning often to optimize cooking and browning.You may also broil, or roast the chicken in a hot oven (425 degrees F).
6. In a small sauce pan simmer the remaining marinade and the one from the chicken for about 7 minutes. Serve with the chicken or mix it before serving with the plantains.