# Sausage, Mushroom, and Black Olive White Pizzas {#whitepizzas}

## Ingredients

- 0.25	cups,	grated parmesan  
- 7	tablespoons,	olive oil  
- 1 clove, garlic (chopped)
- 1,  ciabatta baguette (halved)
- 2, 		 Italian-style chicken sausage links (fully cooked, thinly sliced)
- 0.75	cups,	 mushrooms (sliced)
- 0.25	cups,	sliced black olives  
- 1.5	cups,	 mozzarella (shredded)
- 4 cups,	baby spinach  
- 1	tablespoon,	lemon juice  
- 0.5	teaspoons,	red pepper flakes (optional)

## Instructions

1. Preheat oven to 425F. Stir together Parmesan, 3 tablespoons olive oil, and chopped garlic clove.
2. Halve ciabatta baguette lengthwise and cut into 4 pieces. Place on a foil-lined baking sheet and top with cheese mixture. Top with Italian-style chicken sausage links, mushrooms, and black olives. Sprinkle with shredded mozzarella. Bake until golden, 10 to 12 minutes.
3. Meanwhile, toss together baby spinach, lemon juice and olive oil, and red pepper flakes (optional). Season with kosher salt and black pepper. Top pizza with spinach mixture. Serve immediately.